### ISSUE TITLE
Deleted files are listed, but inaccessible in Docker images using grootfs

### ISSUE THREAD

**Issue by bandesz** [cloudfoundry/garden-runc-release#77] opened 2018-05-11 14:16 UTC
# Description

We have a Docker image where we delete some files during the build. Those files are still listed on the filesystem, but inacessible.

The same Docker image worked on 1.12.1.

# Environment

* garden-runc-release version: 1.13.1
* IaaS: Custom (GOV.UK GDS PaaS)
* Stemcell version: 3541.12
* Kernel version: 4.4.0-119-generic

We are using cf-deployment 1.28.0 at the moment and don't change any of the grootfs settings.

# Steps to reproduce

Dockerfile:

```
FROM tomcat:8.5.23-jre8-alpine
RUN rm -rf /usr/local/tomcat/webapps/*
CMD ["sleep", "1d"]
```

Commands to run:
```
bandesz:~/repos/gds/docker-test$ cf push docker-test --docker-image bandesz/tomcat-test -u process
bandesz:~/repos/gds/docker-test$ cf ssh docker-test
bash-4.3# ls -la /usr/local/tomcat/webapps
ls: /usr/local/tomcat/webapps/ROOT: No such file or directory
ls: /usr/local/tomcat/webapps/docs: No such file or directory
ls: /usr/local/tomcat/webapps/examples: No such file or directory
ls: /usr/local/tomcat/webapps/host-manager: No such file or directory
ls: /usr/local/tomcat/webapps/manager: No such file or directory
total 0
drwxr-x---    1 root     root            76 May 11 14:00 .
drwxr-xr-x    1 root     root            20 May 11 14:00 ..
```

# Logs

I checked `/var/vcap/sys/log/garden` but nothing relevant were logged.

We might have some sensitive information in other system logs, therefore I'm not including them.

# Docker image

I created one for testing: bandesz/tomcat-test

**Comment by williammartin** [comment] 2018-05-11 15:03
Yep, I can reproduce this with the Dockerfile in the previous comment:

```
 2018-05-11 16:01:41 ruby 2.4.1p111 piv-ws-eelpieisland in ~/workspace/garden-runc-release
± db+wm |develop ✓| → gaol create -n lsbug -r docker://cfgarden/lsbug
lsbug

 2018-05-11 16:02:02 ruby 2.4.1p111 piv-ws-eelpieisland in ~/workspace/garden-runc-release
± db+wm |develop ✓| → gaol run -a -c "ls /test/foo" lsbug
4
ls: /test/foo/1: No such file or directory
ls: /test/foo/2: No such file or directory
ls: /test/foo/bar: No such file or directory
```

**Comment by williammartin** [comment] 2018-05-11 15:18
This was definitely introduced between 1.12.1 and 1.13.0 (checked even though this release was pulled)

**Comment by keymon** [comment] 2018-05-11 15:27
For the record, a workaround could be [flatten the image](https://stackoverflow.com/questions/22713551/how-to-flatten-a-docker-image), [for instance by using multi-stage dockerfiles](https://stackoverflow.com/a/44273998/395686):

```
FROM alpine

RUN mkdir -p /test/foo && \
    touch /test/foo/1 /test/foo/2 && \
    mkdir -p /test/foo/bar && \
    touch /test/foo/bar/3
RUN rm -rf /test/foo/*

FROM scratch
COPY --from=0 / /

ENTRYPOINT ["/bin/sh", "-c", "ls /test/foo && sleep 24000"]
```

**Comment by williammartin** [comment] 2018-05-11 15:43
This is the responsible commit https://github.com/cloudfoundry/garden-runc-release/commit/55712b887dc0ca2fff046321b87313e51d563933

**Comment by williammartin** [comment] 2018-05-11 16:14
This is an even simpler reproduction:

```
FROM alpine

RUN mkdir -p /test/foo && \
   touch /test/foo/1 /test/foo/2
RUN rm -rf /test/foo/2

ENTRYPOINT ["/bin/sh", "-c", "ls /test/foo && sleep 24000"]
```

**Comment by BooleanCat** [comment] 2018-06-05 09:15
@bandesz based on the linked PR in alphagov/paas-cf, it looks like this is resolved.

Are you happy to close this?

**Comment by teddyking** [comment] 2018-06-06 10:12
Just for reference, this issue can also present the following symptom:

**Comment by bandesz** [comment] 2018-06-13 10:55
@BooleanCat yes, the the issue can be closed. Thanks for the fix!

**Closed** 2018-06-13 10:55 UTC
Labels: accepted
