### ISSUE TITLE
Failed to destroy container - image directory not empty

### ISSUE THREAD

**Issue by pivotal-peter-ryan** [cloudfoundry/garden-runc-release#143] opened 2019-06-20 11:01 UTC
Failed to destroy container - image directory not empty

## Description
Rep logs show that it cant destroy the container  because it cant delete the image path:
```
rep.container-reaper.reap-extra-garden-containers.failed-to-destroy-container","data":{"error":"running image plugin destroy: deleting image path\n: exit status 1","handle":"68c99693-60b2-4d94-69aa-9ae8","session":"10.205597"}
```

Garden logs says that it cant delete the directory because it not empty:
```
guardian.destroy.volumizer.image-plugin-destroy.grootfs.delete.groot-deleting.deleting-image.overlayxfs-destroying-image.removing-image-path-failed","log_level":2,"data":{"error":"directory not empty","handle":"68c99693-60b2-4d94-69aa-9ae8","id":"68c99693-60b2-4d94-69aa-9ae8","imageID":"68c99693-60b2-4d94-69aa-9ae8","imagePath":"/var/vcap/data/grootfs/store/unprivileged/images/68c99693-60b2-4d94-69aa-9ae8","original_timestamp":"2019-06-19T04:42:22.26589312Z","session":"7816822.2.1","storePath":"/var/vcap/data/grootfs/store/unprivileged"}
```

Not files in the directory above:
```
ls -alrt /var/vcap/data/grootfs/store/unprivileged/images/68c99693-60b2-4d94-69aa-9ae8
total 4
drwxr-xr-x  1 4294967294 4294967294    6 Apr  6 17:49 rootfs
drwx------  3 4294967294 4294967294   20 Apr  6 17:49 .
drwxr-xr-x 44 4294967294 4294967294 4096 May 15 13:59 ..
```

Also note that the image_info is not present:
```
ls -l /var/vcap/data/grootfs/store/unprivileged/images/68c99693-60b2-4d94-69aa-9ae8/image_info
ls: cannot access '/var/vcap/data/grootfs/store/unprivileged/images/68c99693-60b2-4d94-69aa-9ae8/image_info': No such file or directory
```

## Environment

garden-runc v1.16.8
IaaS : vSphere

**Comment by gcapizzi** [comment] 2019-07-12 14:32
@pivotal-peter-ryan hi! Unfortunately we were unable to get to the bottom of the issue looking at the output of `dontpanic`. We believe it would be useful to get the output of `ls -lai /var/vcap/data/grootfs/store/unprivileged/images/<CONTAINER_ID>`, but this has to be done close to the occurrence of the issue, together with `dontpanic`. Can you do this the next time the issue occurs?

**Comment by julz** [comment] 2019-07-29 13:09
Closing since we were unable to reproduce. Please re-open if we find a reproduction or a problematic environment we can investigate.

**Closed by julz** 2019-07-29 13:09 UTC
Labels: unscheduled
