### ISSUE TITLE
Container left cgroup

### ISSUE THREAD

**Issue by chenweienn** [cloudfoundry/garden-runc-release#146] opened 2019-07-31 12:35 UTC
## Description

At stemcell 97.106 and 97.113, we have observed container metric `cpuPercentage` being constant zero. Ram/disk usage are non-zero fixed values, not changing.

`/sys/fs/cgroup/cpu,cpuacct/garden/5c84e0b5-47bb-48fe-6f8c-635c/cpuacct.usage` is NOT increasing. 
`/sys/fs/cgroup/cpu,cpuacct/garden/5c84e0b5-47bb-48fe-6f8c-635c/tasks` is empty.

At the same time, I am able to ssh into this container. The container is running well and is serving requests normally.

To reset the container status, we have to run `cf restart-app-instance`. After restart, the container has normal metrics.

## Environment

* garden-runc-release version: 1.16.1
* Enabled configuration: bpm is used. 
* IaaS: vSphere and Azure, both observed the issue
* Stemcell version: 97.106 and 97.113, both observed the issue 
* Kernel version: 4.15.0-50-generic (from 97.106)

## Steps to reproduce

I provided a Pivotal Lab environment to Giuseppe (gcapizzi@pivotal.io). In this lab, the issue is presenting with app _apps-manager-js-green_ in org _system_ / space _system_.
cell guid: compute/e886fea2-618b-4fe2-bcb0-148d1503bf11
App guid: 9190f74d-a0b9-4bbd-aed7-24cfd6e4200c
Instance guid: 5c84e0b5-47bb-48fe-6f8c-635c

## Logs

I uploaded dontpanic data here: https://drive.google.com/open?id=1Hgaw-zZgO4cObp_Yl6iBX-ePML1D8PPg
Giuseppe should be able to download it.

## Cause

It looks that container cpuPercentage is calculated as described in link https://unix.stackexchange.com/questions/450748/calculating-cpu-usage-of-a-cgroup-over-a-period-of-time
If `/sys/fs/cgroup/cpu,cpuacct/garden/5c84e0b5-47bb-48fe-6f8c-635c/cpuacct.usage` is NOT increasing, cpuPercentage would be zero.
But why does the container leave its cgroups?

**Comment by julz** [comment] 2019-08-02 12:43
Hi @chenweienn - I suspect this is due to an incompatibility between systemd behaviour in recent stemcells and old versions of Garden (systemd will move processes around in cgroups unless explicitly told not to). This was fixed in https://github.com/cloudfoundry/garden-runc-release/releases/tag/v1.18.1 and your issue above says you have 1.16.1. 

I'm going to close this issue but please re-open/create a new issue if you are able to reproduce with a recent garden version. Thanks!

**Closed by julz** 2019-08-02 12:43 UTC
Labels: unscheduled
