### ISSUE TITLE
Garden containerd hangs destroying container (with hung volume mounts)

### ISSUE THREAD

**Issue by paulcwarren** [cloudfoundry/garden-runc-release#111] opened 2018-12-10 20:32 UTC
## Description
Persi team is seeing a failure in our [acceptance tests](https://github.com/cloudfoundry/persi-acceptance-tests/blob/72ac5bd8b303a2d4ea682663a85105b27d46f09e/persi_acceptance_test.go#L425).  This test is checking that we clean up volume mounts cleanly and the way we do that is to create an app with a volume mount, stop the nfs server, attempt to write to that volume and then stop the app.  The stuck volume mount causes [container destruction](https://github.com/cloudfoundry/garden/blob/62470dc86365fb365be099df5c4b59650d695c4b/client.go#L40) to fail (and always has done).  With garden runc, `Destroy` used to timeout after 10 seconds (from memory).  Garden containerd appears to hang, possibly indefinately (although we didnt wait forever...obviously!).   As a result the [defer code in the executor](https://github.com/cloudfoundry/executor/blob/97d9e0e7f840197402d818792ae86928f95fb810/depot/containerstore/storenode.go#L599) doesn't get run anymore.  

## Environment

* garden-runc-release version: 1.17.1
* IaaS: GCP
* Stemcell version: Xenial 170.12
* Kernel version: 4.15.0-42-generic

## Steps to reproduce
This is a rough guestimate of how to repro it using just garden containers:
1. Create a volume mount on the VM
2. Create a container and bind mount that volume into the container
3. Stop the nfs server that is serving that volume mount 
4. From inside the container attempt to write to the volume (this will hang)
5. Destroy the container

Expected Behavior with garden runc was that the `Destroy` call timed out after 10s

Actual behavior with garden containerd is that the `Destroy` call hangs indefinately.

Our testing was based on [this application](https://github.com/cloudfoundry/persi-acceptance-tests/tree/master/assets/pora) pushed to cf.

## Logs
n/a

## Docker image (if relevant)
n/a

## Cause
Unknown

## Resolution
Unknown

Paul @davewalter @julian-hj

**Comment by julian-hj** [comment] 2018-12-11 17:02
I suspect this is related to #108

**Comment by danail-branekov** [comment] 2019-01-25 10:03
Hi @paulcwarren,
There is a new Garden Runc release 1.18.0 that potentially fixes the issue. Could you please verify that it works on your end?

Note that in order to upgrade to GRR 1.18.0 you would also need to bump cf-deployment to 7.1.0.

Thanks!

**Comment by danail-branekov** [comment] 2019-01-25 10:06
Duplicate of #108 

As @julian-hj pointed out, this issue looks like being a duplicate of #108, hence closing. Feel free to reopen if GRR 1.18.0 does not fix it.

**Closed by danail-branekov** 2019-01-25 10:06 UTC
Labels: scheduled

**Comment by davewalter** [comment] 2019-01-26 01:08
Thanks @danail-branekov. We have removed the `use-native-garden-runc-runner.yml` ops-file from our CI deployments are are running them now. We have already consumed `cf-deployment` v7.1.0 so hopefully everything *just works*:tm:.

Regards,
Dave

**Comment by paulcwarren** [comment] 2019-01-29 21:53
Hi @danail-branekov @davewalter and I have been running with GRR 1.18.0 in our pipeline for a few days to exercise it a bit and been periodically checking the cells.  Done a `bosh -d cf restart diego-cell` and so on.  We dont see any sign of the previous behavior now so from our perspective it looks good.  thx.
