### ISSUE TITLE
Garden does not come up after a rolling cell deploy

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/garden-runc-release#131] opened 2019-03-06 16:00 UTC
## Description
When doing a deploy that updated "BPM" from 1.0.0 to 1.0.3 the garden job did not start.

```
diego-cell/3c0ffe86-18cf-4fb6-bd31-87cea264fff4:/var/vcap/bosh_ssh/bosh_dff921e5e681477# monit summary
The Monit daemon 5.2.5 uptime: 10h 15m

Process 'containerd'                running
Process 'garden'                    Connection failed
Process 'rep'                       running
Process 'route_emitter'             running
Process 'netmon'                    running
Process 'vxlan-policy-agent'        running
```

## Environment

* garden-runc-release version: 1.18.2
* Enabled configuration: containerd
* IaaS: SoftLayer
* Stemcell version: Xenial 250.4.1
* Kernel version: 4.15.0-43-generic

## Steps to reproduce
We just did a new deploy with the following diff ...

```
  releases:
  - name: bpm
-   sha1: 42b95d4a0d6d15dd0b0ead62418ffb56208e2307
-   url: http://10.106.192.96/releases/ibm-deployment/bpm/develop-next/1.0.0/bpm-release-1.0.0.tgz
+   url: http://10.106.192.96/releases/ibm-deployment/bpm/develop-next/1.0.3/bpm-release-1.0.3.tgz
-   version: 1.0.0
+   version: 1.0.3
```

## Logs
```
## Date
## Uptime
Wed Mar  6 15:54:44 UTC 2019
 15:54:44 up 1 day,  7:45,  1 user,  load average: 3.92, 4.04, 3.98
## Garden Version
1442ad40796044615cb2a597cac1dd031767f388
## Hostname
65acca7d-2f66-447c-aa5e-6e322614b0b6
## Memory Usage
              total        used        free      shared  buff/cache   available
Mem:          32163         715        3456         389       27990       30204
Swap:         32162          40       32122
Total:        64326         756       35579
## Disk Usage
Filesystem      Size  Used Avail Use% Mounted on
udev             16G     0   16G   0% /dev
tmpfs           3.2G  393M  2.8G  13% /run
/dev/xvda1       25G  2.4G   21G  10% /
tmpfs            16G     0   16G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/xvdc2      265G   84G  167G  34% /var/vcap/data
tmpfs           1.0M   72K  952K   8% /var/vcap/data/sys/run
/dev/loop0      265G  7.1G  258G   3% /var/vcap/data/grootfs/store/unprivileged
/dev/loop1      265G  2.1G  263G   1% /var/vcap/data/grootfs/store/privileged
overlay         256M  221M   36M  87% /var/vcap/data/grootfs/store/unprivileged/images/b4a481bc-7a0f-4cdf-782e-6567/rootfs
overlay         265G  7.1G  258G   3% /var/vcap/data/grootfs/store/unprivileged/images/b4a481bc-7a0f-4cdf-782e-6567-envoy/rootfs
overlay         128M   11M  118M   9% /var/vcap/data/grootfs/store/unprivileged/images/c5dee24a-581d-4b3d-685b-53aa/rootfs
overlay         265G  7.1G  258G   3% /var/vcap/data/grootfs/store/unprivileged/images/c5dee24a-581d-4b3d-685b-53aa-envoy/rootfs
overlay         1.0G  182M  843M  18% /var/vcap/data/grootfs/store/unprivileged/images/186e1b4d-c111-4ee8-7dfa-c7a1/rootfs
overlay         265G  7.1G  258G   3% /var/vcap/data/grootfs/store/unprivileged/images/186e1b4d-c111-4ee8-7dfa-c7a1-envoy/rootfs
tmpfs            16G     0   16G   0% /var/vcap/data/bpm/tmpworkaround
tmpfs           2.8M     0  2.8M   0% /var/vcap/data/rep/shared/garden/instance_identity
## Kernel Details
Linux 65acca7d-2f66-447c-aa5e-6e322614b0b6 4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
## Monit Summary
The Monit daemon 5.2.5 uptime: 10h 19m

Process 'containerd'                running
Process 'garden'                    Connection failed
Process 'rep'                       running
Process 'route_emitter'             running
Process 'netmon'                    running
Process 'vxlan-policy-agent'        running
Process 'silk-daemon'               running
Process 'bosh-dns-adapter'          running
Process 'consul_agent'              running
Process 'loggregator_agent'         running
Process 'loggr-expvar-forwarder'    running
Process 'bosh-dns'                  running
Process 'bosh-dns-resolvconf'       running
Process 'bosh-dns-healthcheck'      running
Process 'mod_vms'                   running
Process 'sssd'                      running
Process 'incrond'                   running
Process 'filebeat'                  running
System 'system_localhost'           running
## Number of Containers
18
## Number of Open Files

```

## Docker image (if relevant)
N/A

## Cause
?

## Resolution
reboot of VM got it healthy again

**Comment by Callisto13** [comment] 2019-03-07 09:50
`os-report` was shared out of band. Significant content:

```sh
os-report/ $ cat ps-info.log | grep 'D '
    PID     TID    PPID USER        COMMAND         S WCHAN                                 STARTED
  51574   51574   50927 4294967294  garden-init     D refrigerator         Wed Mar  6 03:51:50 2019
  72609   72609   70577 4294967294  sh              D refrigerator         Wed Mar  6 03:53:08 2019
  77227   77227   77189 2000        runc:[2:INIT]   D flush_old_exec       Wed Mar  6 03:53:32 2019
  77227   77229   77189 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 03:53:32 2019
  77227   77273   77189 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 03:53:33 2019
  77227   77274   77189 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 03:53:33 2019
  77227   77278   77189 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 03:53:33 2019
  77227   77282   77189 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 03:53:33 2019
  77227   77478   77189 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 03:53:34 2019
  77227   77685   77189 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 03:53:35 2019
  77227   77686   77189 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 03:53:35 2019
  77227   77705   77189 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 03:53:35 2019
  78945   78945   72609 4294967294  envoy           D refrigerator         Wed Mar  6 03:53:41 2019
  78945   79122   72609 4294967294  grpc_global_tim D refrigerator         Wed Mar  6 03:53:41 2019
  78945   79129   72609 4294967294  envoy           D refrigerator         Wed Mar  6 03:53:41 2019
  78945   79135   72609 4294967294  envoy           D refrigerator         Wed Mar  6 03:53:41 2019
  78945   79136   72609 4294967294  envoy           D refrigerator         Wed Mar  6 03:53:41 2019
  78945   79137   72609 4294967294  envoy           D refrigerator         Wed Mar  6 03:53:41 2019
  78945   79138   72609 4294967294  envoy           D refrigerator         Wed Mar  6 03:53:41 2019
  78945   79146   72609 4294967294  envoy           D refrigerator         Wed Mar  6 03:53:41 2019
  86476   86476   51574 2000        bash            D refrigerator         Wed Mar  6 03:54:05 2019
  86917   86917   86476 2000        ruby            D refrigerator         Wed Mar  6 03:54:06 2019
  86917   89282   86476 2000        ruby-timer-thr  D refrigerator         Wed Mar  6 03:54:12 2019
2841730 2841730 2841664 4294967294  garden-init     D refrigerator         Wed Mar  6 02:33:19 2019
2845623 2845623 2845190 4294967294  runc:[2:INIT]   D flush_old_exec       Wed Mar  6 02:33:34 2019
2845623 2845633 2845190 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 02:33:34 2019
2845623 2845634 2845190 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 02:33:34 2019
2845623 2845635 2845190 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 02:33:34 2019
2845623 2845636 2845190 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 02:33:34 2019
2845623 2845639 2845190 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 02:33:34 2019
3954970 3954970 3954893 4294967294  garden-init     D refrigerator         Wed Mar  6 03:33:47 2019
3960481 3960481 3960450 2000        runc:[2:INIT]   D flush_old_exec       Wed Mar  6 03:34:05 2019
3960481 3960488 3960450 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 03:34:05 2019
3960481 3960495 3960450 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 03:34:05 2019
3960481 3960506 3960450 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 03:34:05 2019
3960481 3960521 3960450 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 03:34:05 2019
3960736 3960736 3960588 2000        diego-sshd      D refrigerator         Wed Mar  6 03:34:06 2019
3960947 3960947 3960693 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 03:34:07 2019
3960947 3960995 3960693 4294967294  runc:[2:INIT]   D refrigerator         Wed Mar  6 03:34:07 2019

os-report/ $ less ps-forest.log
root     2841664  0.0  0.0 109288 31444 ?        Sl   02:33   0:14 containerd-shim -namespace garden -workdir /var/vcap/data/containerd/root/io.containerd.runtime.v1.linux/garden/b4a481bc-7a0f-4cdf-782e-6567 -address /var/vcap/sys/run/containerd/containerd.sock -containerd-binary /var/vcap/data/packages/containerd/4cc9b768e0c7312833088b450b52e1764b16f301/bin/containerd
4294967+ 2841730  0.0  0.0   1120     0 ?        Ds   02:33   0:00  \_ /tmp/garden-init
root     2846355 18.2  0.0 233292 11296 ?        Sl   02:33 147:27  \_ runc --root /run/containerd/runc/garden --log /var/vcap/data/containerd/state/io.containerd.runtime.v1.linux/garden/b4a481bc-7a0f-4cdf-782e-6567/log.json --log-format json kill --all b4a481bc-7a0f-4cdf-782e-6567 9

```



Closing this as is a dupe of https://github.com/cloudfoundry/garden-runc-release/issues/121.

**Closed by Callisto13** 2019-03-07 09:50 UTC
Labels: delivered
