### ISSUE TITLE
After reboot diego_cell "garden" service failed to come UP and waiting for containerd to become available

### ISSUE THREAD

**Issue by Nilesh7756** [cloudfoundry/garden-runc-release#194] opened 2021-07-01 11:46 UTC
## Description

Provide as much detail about the issue as possible.

We have deployed TasforVMs (2.11.1) + NSX-T + NCP (3.1.2) ENV.

Here "Garden" service fail to UP after DIEGO_CELL Power-Off/Power-On from VC or simply reboot from Diego_cell vm

> Process 'garden'                    not monitored

> 2021-07-01T09:13:52.131876551Z waiting for containerd to become available

> {"timestamp":"2021-07-01T09:11:03.572367844Z","level":"info","source":"guardian","message":"guardian.api.garden-server.waiting-for-connections-to-close","data":{"session":"1.1"}}

We observed this issue on  TasforVMs (2.11.0) also.

## Environment

* garden-runc-release version:  bf4c737f2bc490aa82b8883e2c8964680236a8df
* Enabled configuration: 
* IaaS:
* Stemcell version:  ubuntu-xenial 621.125
* Kernel version:  Linux d75c19a3-324e-46af-916e-22760f86c251 4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 

diego_cell/6e5e857b-5115-48fd-b40c-939f343b3f51:~# /var/vcap/packages/dontpanic/bin/dontpanic
<Useful information below, please copy-paste from here>
- Date
Thu Jul  1 09:19:03 UTC 2021
- Uptime
 09:19:03 up 6 min,  1 user,  load average: 0.16, 0.35, 0.18
-  Garden Version
bf4c737f2bc490aa82b8883e2c8964680236a8df
- Hostname
d75c19a3-324e-46af-916e-22760f86c251
- Memory Usage
              total        used        free      shared  buff/cache   available
Mem:           7977         373        6915          31         687        7288
Swap:          7976           0        7976
Total:        15954         373       14892
- Kernel Details
2021 x86_64 x86_64 x86_64 GNU/Linux
-  Monit Summary
The Monit daemon 5.2.5 uptime: 5m 

Process 'rep'                       running
Process 'route_emitter'             running
Process 'garden'                    not monitored
Process 'loggregator_agent'         running
Process 'loggr-syslog-agent'        running
Process 'metrics-discovery-registrar' Does not exist
Process 'metrics-agent'             running
Process 'loggr-forwarder-agent'     running
Process 'prom_scraper'              running
Process 'nfsv3driver'               running
Process 'smbdriver'                 running
Process 'bosh-dns-adapter'          running
Process 'iptables-logger'           running
Process 'bosh-dns'                  running
Process 'bosh-dns-resolvconf'       running
Process 'bosh-dns-healthcheck'      running
Process 'system-metrics-agent'      running
Process 'ovsdb-server'              running
Process 'ovs-vswitchd'              running
Process 'nsx-node-agent'            running
System 'system_localhost'           running
- Number of Open Files
10311
- Max Number of Open Files
811736

>> Mount Table failed: cat: /proc//mountinfo: No such file or directory

- Garden Containers
>> Garden Containers failed: 
<Report Complete. Archive Created: /var/vcap/data/tmp/os-report-d75c19a3-324e-46af-916e-22760f86c251-2021-07-01-09-19-03.269145952.tar.gz>

## Logs

We have reboot Diego_cell around "2021-07-01T09:10:xx"

> containerd.stderr.log 
time="2021-07-01T09:13:52.436264389Z" level=info msg="starting containerd" revision=.m version=
time="2021-07-01T09:13:52.448568629Z" level=info msg="loading plugin \"io.containerd.service.v1.introspection-service\"..." type=io.containerd.service.v1
time="2021-07-01T09:13:52.448662484Z" level=info msg="loading plugin \"io.containerd.content.v1.content\"..." type=io.containerd.content.v1
time="2021-07-01T09:13:52.470435646Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.native\"..." type=io.containerd.snapshotter.v1
time="2021-07-01T09:13:52.489232795Z" level=info msg="loading plugin \"io.containerd.metadata.v1.bolt\"..." type=io.containerd.metadata.v1
time="2021-07-01T09:13:52.489268606Z" level=info msg="metadata content store policy set" policy=shared
time="2021-07-01T09:13:52.496592651Z" level=info msg="loading plugin \"io.containerd.service.v1.containers-service\"..." type=io.containerd.service.v1
time="2021-07-01T09:13:52.496618496Z" level=info msg="loading plugin \"io.containerd.service.v1.content-service\"..." type=io.containerd.service.v1
time="2021-07-01T09:13:52.496633739Z" level=info msg="loading plugin \"io.containerd.runtime.v1.linux\"..." type=io.containerd.runtime.v1
time="2021-07-01T09:13:52.511256779Z" level=info msg="loading plugin \"io.containerd.runtime.v2.task\"..." type=io.containerd.runtime.v2
time="2021-07-01T09:15:32.644742803Z" level=warning msg="cleaning up after shim disconnected" id=00fcbb48-a39c-4780-4724-5eb2 namespace=garden
time="2021-07-01T09:15:32.644939639Z" level=info msg="cleaning up dead shim"
time="2021-07-01T09:15:38.276816062Z" level=warning msg="cleanup warnings time=\"2021-07-01T09:15:34Z\" level=info msg=\"starting signal loop\" namespace=garden pid=6723\n"
time="2021-07-01T09:17:18.380118819Z" level=warning msg="cleaning up after shim disconnected" id=0199b20a-dcc9-486d-4f1b-d22b namespace=garden
time="2021-07-01T09:17:18.380152840Z" level=info msg="cleaning up dead shim"

> containerd_ctl.log 
2021-07-01T09:11:03.931770499Z containerd stopping
2021-07-01T09:11:03.953214682Z stopping containerd
2021-07-01T09:11:04.036552695Z containerd stopped
2021-07-01T09:13:47.254992274Z containerd starting
2021-07-01T09:13:47.268334180Z starting containerd
2021-07-01T09:13:47.273576933Z running containerd
2021-07-01T09:13:52.131876551Z waiting for containerd to become available
2021-07-01T09:13:52.384837885Z waiting for containerd to become available

> garden.stdout.log
{"timestamp":"2021-07-01T09:11:03.572367844Z","level":"info","source":"guardian","message":"guardian.api.garden-server.waiting-for-connections-to-close","data":{"session":"1.1"}}
{"timestamp":"2021-07-01T09:11:03.572437172Z","level":"info","source":"guardian","message":"guardian.api.garden-server.stopping-backend","data":{"session":"1.1"}}
{"timestamp":"2021-07-01T09:11:03.572470626Z","level":"info","source":"guardian","message":"guardian.api.garden-server.stopped","data":{"session":"1.1"}}
{"timestamp":"2021-07-01T09:11:03.597594769Z","level":"[os-report-d75c19a3-324e-46af-916e-22760f86c251-2021-07-01-09-19-03.269145952.tar.gz](https://github.com/cloudfoundry/garden-runc-release/files/6747821/os-report-d75c19a3-324e-46af-916e-22760f86c251-2021-07-01-09-19-03.269145952.tar.gz)","source":"guardian","message":"guardian.start.event service received an error","data":{"[os-report-d75c19a3-324e-46af-916e-22760f86c251-2021-07-01-09-19-03.269145952.tar.gz](https://github.com/cloudfoundry/garden-runc-release/files/6747821/os-report-d75c19a3-324e-46af-916e-22760f86c251-2021-07-01-09-19-03.269145952.tar.gz)":"rpc error: code = Canceled desc = grpc: the client connection is closing","session":"4"}}
{"timestamp":"2021-07-01T09:11:03.597725460Z","level":"error","source":"guardian","message":"guardian.start.event service received an error","data":{"error":"rpc error: code = Canceled desc = grpc: the client connection is closing","session":"4"}}
{"timestamp":"2021-07-01T09:11:03.597775108Z","level":"error","source":"guardian","message":"guardian.start.event service received an error","data":{"error":"rpc error: code = Canceled desc = grpc: the client connection is closing","session":"4"}}

**Comment by gcapizzi** [comment] 2021-07-01 15:08
Hi @Nilesh7756! 
We have looked into this and we think the problem is caused by restarting the machine. `containerd` has a reconciliation mechanism that kicks in when it starts, and it checks if any of the containers registered as running are actually still running. If not, they'll be unregistered. Unfortunately this operation takes 100 seconds to time out.

If you restart the cell, you will kill all containers, which means once back up, `containerd` will take 100 seconds per container running before the restart to reconcile its internal state with the state of the machine.By looking at the logs, this machine had quite a few containers running, so `containerd` will take a long time to come back up. This in turn might hit some `monit` timeouts which might make the operation even slower.

We don't have a solution for this at the moment, cell restarts are just not supported very well at the moment. The system should _eventually_ come back up, but it might take it some time. Instead of restarting the cell, you could either:
* `monit restart` Garden, which will also restart `containerd` but leave the containers running;
* `bosh recreate` the cell, so that `containerd`'s gets a clean state and no reconciliation is necessary once the machine is back up.

**Comment by Nilesh7756** [comment] 2021-07-02 05:40
Diego_cell rebooted at  "Thu Jul 09:10:xx UTC 2021" and when we checked at "Thu Jul  1 17:52:57 UTC 2021" still Garden service seems to be in failed state.

Before reboot diego_cell we have 88 container app running on ENV, `containerd` has a reconciliation mechanism that kicks in when it starts and `containerd` will take 100 seconds per container. So according to this almost for 2 and half hours diego_cell will be in bad state and then after `garden` service should be UP running. 

**Observation**: Here almost 8 hours after reboot still Garden service was found in failed state. Then after `monit restart garden`  service came UP and running.

diego_cell/6e5e857b-5115-48fd-b40c-939f343b3f51:~# date
Thu Jul  1 17:52:57 UTC 2021

diego_cell/6e5e857b-5115-48fd-b40c-939f343b3f51:~# monit summary
The Monit daemon 5.2.5 uptime: 8h 39m 

Process 'rep'                       running
Process 'route_emitter'             running
Process 'garden'                    Execution failed
Process 'loggregator_agent'         running
Process 'loggr-syslog-agent'        running
Process 'metrics-discovery-registrar' running
Process 'metrics-agent'             running
Process 'loggr-forwarder-agent'     running
Process 'prom_scraper'              running
Process 'nfsv3driver'               running
Process 'smbdriver'                 running
Process 'bosh-dns-adapter'          running
Process 'iptables-logger'           running
Process 'bosh-dns'                  running
Process 'bosh-dns-resolvconf'       running
Process 'bosh-dns-healthcheck'      running
Process 'system-metrics-agent'      running
Process 'ovsdb-server'              running
Process 'ovs-vswitchd'              running
Process 'nsx-node-agent'            running
System 'system_localhost'           running
diego_cell/6e5e857b-5115-48fd-b40c-939f343b3f51:~#

**Comment by gcapizzi** [comment] 2021-07-02 08:55
This might be due to `monit` giving up on Garden after a few timeouts:

```
Process 'garden' Execution failed
```

So when I said:

> The system should eventually come back up, but it might take it some time. 

I was clearly wrong 😓 `monit` won't try to restart Garden/`containerd` for 2 hours, it will give up a lot earlier than that.

The only way to get this cell back is to recreate it. In the future, please don't restart Diego cells. Either recreate them or `monit restart garden`.

**Comment by gcapizzi** [comment] 2021-07-05 14:22
We have learned more about this and opened a [new issue](https://github.com/cloudfoundry/garden-runc-release/issues/195), so closing this and moving the conversation there!

**Closed by gcapizzi** 2021-07-05 14:22 UTC
