### ISSUE TITLE
Garden failed to clean up containers on startup

### ISSUE THREAD

**Issue by sjolicoeur** [cloudfoundry/garden-runc-release#82] opened 2018-07-02 19:29 UTC
# Description

On a re-deploy a diego-cell took 51 min to come back up. The rep left quite a few containers laying around after evacuation. On start-up of the cell after the update we saw that Garden deleted peas containers but not application containers that were orphaned. 

We expected garden to have gone into a clean up loop to delete and destroy all the orphaned containers on the cell. 

We know that `destroy_containers_on_start` is set to `true`, as such we do  expect to see log lines related to: https://github.com/cloudfoundry/guardian/blob/6101577ecf3aa2a29e109a2a1380314cacc7df37/gardener/gardener.go#L479
but we do not. 

However we see that garden did not delete any containers, and the slow startup time was due to the rep's own clean up [loop](https://github.com/cloudfoundry/executor/blob/e6cf2660bc4fe97c6f25255125facbb0ca4ccb65/initializer/initializer.go#L454-L477) running.

We are puzzled as to how we can end up in this state where garden is not able to immediately find the number of orphaned containers but later upon the rep's request give out a number of orphaned containers?

# Environment

* garden-runc-release version: 1.10.0
* IaaS: unknown
* Stemcell version:  3468.21+
* Kernel version: unknown

# Steps to reproduce

[...]

# Logs

Some log highlights: 
```
{"timestamp":"1529914162.323287249","source":"guardian","message":"guardian.start.starting","log_level":1,"data":{"session":"4"}}
{"timestamp":"1529914162.323378801","source":"guardian","message":"guardian.start.clean-all-peas.start","log_level":1,"data":{"session":"4.1"}}
[...]
{"timestamp":"1529914162.389882088","source":"guardian","message":"guardian.start.completed","log_level":1,"data":{"session":"4"}}
[...]
{"timestamp":"1529914162.395313263","source":"guardian","message":"guardian.list-containers.starting","log_level":1,"data":{"session":"5"}}
[...]
{"timestamp":"1529914162.399815083","source":"guardian","message":"guardian.list-containers.finished","log_level":1,"data":{"session":"5"}}
[...]
{"timestamp":"1529914162.427858829","source":"guardian","message":"guardian.started","log_level":1,"data":{"addr":"/var/vcap/data/garden/garden.sock","network":"unix"}}
[...]
{"timestamp":"1529914164.685106754","source":"guardian","message":"guardian.list-containers.starting","log_level":1,"data":{"session":"6"}}
{"timestamp":"1529914164.685930967","source":"guardian","message":"guardian.list-containers.finished","log_level":1,"data":{"session":"6"}}
{"timestamp":"1529914164.686795473","source":"guardian","message":"guardian.destroy.start","log_level":1,"data":{"handle":"0016fb0d-1ab7-4c43-7d5a-5004","session":"7"}}


{"timestamp":"1529914164.682427406","source":"rep","message":"rep.wait-for-garden.ping-garden","log_level":1,"data":{"initialTime:":"2018-06-25T08:09:24.682211759Z","session":"1","wait-time-ns:":207110}}
{"timestamp":"1529914164.684116840","source":"rep","message":"rep.wait-for-garden.ping-garden-success","log_level":1,"data":{"initialTime:":"2018-06-25T08:09:24.682211759Z","session":"1","wait-time-ns:":1885043}}
{"timestamp":"1529914164.684298515","source":"rep","message":"rep.executor-fetching-containers-to-destroy","log_level":1,"data":{}}
{"timestamp":"1529914164.686308384","source":"rep","message":"rep.executor-fetched-containers-to-destroy","log_level":1,"data":{"num-containers":58}}
{"timestamp":"1529914164.686429977","source":"rep","message":"rep.executor-destroying-container","log_level":1,"data":{"container-handle":"0016fb0d-1ab7-4c43-7d5a-5004"}}
{"timestamp":"1529914225.345789671","source":"rep","message":"rep.executor-destroyed-stray-container","log_level":1,"data":{"handle":"0016fb0d-1ab7-4c43-7d5a-5004"}}
```
We can provide more logs directly via secure file exchange.

# Cause

TBD... maybe resource starvation?

# Resolution

TBD

@sunjayBhatia

**Comment by sunjayBhatia** [comment] 2018-07-02 19:43
In addition to deletion of containers on startup issue, we see many instances of container deletion taking significant time (on the order of 1-2 minutes I believe) and are wondering what factors could contribute to that as well?

**Comment by Callisto13** [comment] 2018-07-05 09:59
I would like to correct the versions given on this issue. The logs contain lines which could not come from Garden-Runc release v1.10.0. Having read various threads surrounding this issue, I believe that these logs (and the others provided us outside this page) are from Garden-Runc version v1.13.3. (The stemcell would therefore be 3541.30).
I understand the sequence of events as following:

- The `diego-cell` (running GRR 1.10.0, Diego-Release 1.29.0 and stemcell 3468.21) failed to come back up after some time during a redeploy.
- Operators checked logs, and observed that Garden had failed to delete application containers which meant that the Diego rep could not evacuate.
- Support staff requested component logs but operators were not in time to download these before they were rotated.
- Operators upgraded their platform to use (among other things) GRR 1.13.3, DR 1.35.5 and stemcell 3541.30.
- Operators performed another redeploy (no version changes, just configuration), and managed to reproduce the issue (cell failed to start after 51 mins). In this occurrence, peas containers were observed as being cleaned up, but not their corresponding application containers.
- Logs were gathered and forwarded to Diego and Garden teams. This issue was opened.
- Operators recreated their cells to clear the issue HOWEVER any further redeploys would result in the cell hanging and applications failing to be evacuated and restarted elsewhere.


I have not yet been able to reproduce the issue, but it seems like the original environment could get back to that state quite easily. If possible, I would like to ask those operators to trigger a redeploy and to then gather more information (If they are not willing to sabotage their production environment, then I just ask that they collect this information should it happen again unintentionally):

1. Gather all component logs from the afflicted VM.
1. Run the following command on the afflicted VM as root, and send the resulting `.tar` to the support team: `curl bit.ly/garden-ordnance-survey -sSfL | bash`
	- If the operators are concerned about running this script, they may either review it first at `bit.ly/garden-ordnance-survey`, or edit the resultant tarball after they have run it (informing us what they have removed). The script is not designed to read anything sensitive, just gather system and garden component information not present in logs.

As there are also logs which describe running out of resources, it would be useful to gather stats about the host (CPU, memory etc). If we could get this data before and during the problem that would be brilliant.

I do not yet have a solid theory for the root cause of the failed cleanup, but I have a couple of thoughts:
- Pea cleanup logic is not a factor: the original occurrence presented in a version which did not clean peas. But..
- ... this does not mean that the _presence_ of peas is not a factor. I will be looking into this today.
- Resource contention is a significant contender and one I will also be looking into today.

wdyt @sunjayBhatia @sjolicoeur ?

**Comment by David-Pivotal** [comment] 2018-07-25 03:10
@Callisto13 Sorry for the late notice. Customer added more memory to the cell by scaling up to 32GB instead of the default 16GB. As a result the time was cut to 6-7 minutes when the cell was restarted. Before making this change, the time was more than 40 minutes.
As customer did not hit this issue, it is a pity that your requested log files were not collected.

**Comment by Callisto13** [comment] 2018-07-25 08:48
Thanks @David-Pivotal!
Sad not to determine the root cause 100% yet, but resource contention is winning ;)

**Comment by julz** [comment] 2018-08-07 13:25
Closing, please do re-open if this reoccurs!

**Closed by julz** 2018-08-07 13:25 UTC
Labels: unscheduled
