### ISSUE TITLE
Started using GrootFS and now see "applying disk limits: disk limit is smaller than volume size"

### ISSUE THREAD

**Issue by williammartin** [cloudfoundry/garden-runc-release#64] opened 2018-03-21 11:58 UTC
### Environment 

I push docker apps to CF. I was on some older version of `garden-runc-release`, that didn't use `GrootFS`. I upgraded to version 1.11.0 of `garden-runc-release`. This also happens when upgrading to versions later than 1.11.0.

### Symptom 

After upgrading, which resulted in using GrootFS for filesystem management, some of my docker apps started failing with the following error message, which I found in `/var/vcap/sys/log/garden/garden.stdout.log`.

```
"error":"running image plugin create: making image: creating image: applying disk limits: disk limit is smaller than volume size\n: exit status 1"
```

My docker images seemed to be an acceptable size before, why are they failing now?

**Comment by Callisto13** [comment] 2018-03-21 14:51
### Cause

This is an interesting one. There is a regression here, but it turns out that in the old filesystem management code (`garden-shed`), we were calculating the size of the layers in docker images incorrectly. `GrootFS` actually calculates sizes correctly now.

### Resolution

The "bug" can be fixed by increasing disk quotas for applications, or reducing the size of docker images.

**Closed by Callisto13** 2018-03-21 14:51 UTC
Labels: in progress
